FROM maven:3-jdk-8 AS builder

WORKDIR /app
RUN apt-get update && apt-get dist-upgrade -y && apt-get install -y openjfx
COPY pom.xml /app/pom.xml
#RUN mvn dependency:copy-dependencies

COPY src /app/src

RUN mvn package

